### ISSUE TITLE
No custom_method module in Ubuntu 18.10

### ISSUE THREAD

**Issue by hyc** [sibradzic/stapmlifier#1]
I thought I'd point this out since your uProf example used Ubuntu 18.10. The ACPI custom_method module doesn't appear to be present in this distro at all.

**Comment by sibradzic** [comment]
oops, damn it, I used the 4.20 ppa when playing with this, assuming that **custom_method** module is available on "normal" kernels, but it is only built by default on ppa (why, Canonical, why?!? :-1::-1::-1:):
```
root@B350GTN:~# grep CONFIG_ACPI_CUSTOM_METHOD /boot/config-4.*
/boot/config-4.18.0-12-generic:# CONFIG_ACPI_CUSTOM_METHOD is not set
/boot/config-4.18.0-13-generic:# CONFIG_ACPI_CUSTOM_METHOD is not set
/boot/config-4.20.0-042000-generic:CONFIG_ACPI_CUSTOM_METHOD=m
```
OK, I'll add the **custom_method** module build instructions in README...

**Comment by sibradzic** [comment]
instructions added
