### ISSUE TITLE
Cannot compile ACPI method on Dell Inspiron 7375

### ISSUE THREAD

**Issue by sockusminimus** [sibradzic/stapmlifier#2]
I am trying to run this on an Inspiron 7375 but unfortunately, I can't compile the custom ACPI method due to the following errors:

```
Compiling custom ACPI method

Intel ACPI Component Architecture
ASL+ Optimizing Compiler/Disassembler version 20180105
Copyright (c) 2000 - 2018 Intel Corporation

stapmlifier.asl      3:   Method (\STPM, 2, Serialized)
Warning  4089 -                      ^ Object is not referenced

stapmlifier.asl     39:     \_SB.ALIB (0x0C, XXAA)
Error    6084 -                    ^ Object does not exist (\_SB.ALIB)

ASL Input:     stapmlifier.asl - 43 lines, 1238 bytes, 13 keywords

Compilation complete. 1 Errors, 1 Warnings, 0 Remarks, 1 Optimizations

```

I have dumped and attached the DSDT table from my system to aid in debugging the error for other similar systems (probably all Dells).

Edit: Zipped up the raw file instead of the decompiled one.  Updated.

[dsdt.zip](https://github.com/sibradzic/stapmlifier/files/2743598/dsdt.zip)

**Comment by sibradzic** [comment]
something is off here, iasl compiler flag `-vw 6084` should totally ignore `6084` error, but you still get it...
can you share you de-compiled DSDT please? Also, does DSDT refer to other methods in SDDTx or similar?
does it refer to ALIB method at all? How about trying `ALIB` instead of `\_SB.ALIB`?

**Comment by sibradzic** [comment]
also, can you try with iasl `20180629`?

**Comment by sockusminimus** [comment]
Thanks for the reply!  I'll try it with iasl 20180629 when I get home.  Check the zip at the bottom of my first post for the decompiled DSDT.

**Comment by sibradzic** [comment]
I could reproduce the issue with iasl 20180105, same failure happens. Version 20180629 or newer works as expected. Updated the README.

**Comment by Falcosc** [comment]
Hi @pauldmartin @sibradzic could one of you tell me how it does look like when Zen+ does reject MP1 calls from ryzenAdj?
I would like to reference your guide for that error case.

I would like to know how Zen+ is able to prevent the change.

It can either periodically overwrite the PM Table value or it could reject MP1 calls from ryzenAdj.

It's easy to test. Disable your ACPI fix, download the latest ryzenAdj and execute:

`ryzenAdj --fast-limit=30000 --dump-table`

The dump will show you the value before and after adjust. If it can change the value for a short period of time, then Zen+ can force power limits maybe only periodically (this would be good news for people how can't follow your guide and would just like to do dirty tricks like reapplying values in a loop)

**Comment by sibradzic** [comment]
Hi @Falcosc . Thanks for you hard work @ [RyzenAdj](https://github.com/FlyGoat/RyzenAdj), much obliged!

> could one of you tell me how it does look like when Zen+ does reject MP1 calls from ryzenAdj?

It is mostly just a theory that nobody had proven so far, but what I think is going on is that some notebooks have special ACPI code that is run periodically and resets the STAPM and PPT to the values provided in BIOS. Some of those notebooks also have special power profile tool (that would only work in Windows) that can set the power profile to "battery-save", "optimal" or "performance", affecting the STAPM & PPT value that is periodically set.

It should be possible to decompile DSDT on such machines and override the ACPI code from forcing STAPM & PPT values, or simply just set the enforced value to the desired one.

About rejecting MP1 calls, I haven't experienced such thing myself, it could be that it is some kind of race between setting MP1 by RyzenAdj and ACPI code...

It is also possible that the power profile is periodically set by some runtime UEFI service other than ACPI, such as SMM or SMBIOS, but if that is true it would be pretty complex to analyse & understand.

I think the best course of action would be to focus on a single notebook and try to decompile its DSDT/ACPI and debug the "power profile" behaviour. After understanding how is this really happening we could think of hot to counter it in RyzenAdj.

**Comment by Falcosc** [comment]
@sibradzic Thanks for your response, I don't need it in detail, it would be already enough to know if they do it via reset and if the reset is happening faster than each 1-2s.

It's enough to disable the ACPI fix and test how long the STAPM and PPT values are persistent. Thank you.
with `--dump-table` you can check if the limit value did change on all platforms.
