### ISSUE TITLE
Manual node question

### ISSUE THREAD

**Issue by ThetaProtocol** [sibradzic/stapmlifier#3]
Is it possible to make the 
`VER=$(cat /proc/AMDPowerProfiler/device)
&& sudo mknod /dev/AMDPowerProfiler -m 666 c $VER 0` command persistent? I'd like for AMD uProf to not make me execute it on every reboot just to see power usage

**Comment by sibradzic** [comment]
Usually, any reasonable kernel driver code would take care of this part, but it seems that `AMDPowerProfiler` module lacks that logic, so you have to do this on your own every time after module has been loaded. It should be easy to cook a boot-time script or systemd module that takes care of that for you.
This repo focuses on how to tweak STAPM via ACPI, μProf stuff is just on the side note, but do you think that the `AMDPowerProfiler` driver loading process should be elaborated more?

**Comment by ThetaProtocol** [comment]
I think how you've outlined the process is more than adequate since most linux people use ubuntu and my issue is a minority one. With regards to the driver, we can just wait until AMD decides how it handles its software for both linux and its mobile chips in general.
