### ISSUE TITLE
STAPM parameters

### ISSUE THREAD

**Issue by Kenryov** [sibradzic/stapmlifier#4]
I used the helper script to set parameters to 45 PPT-fast 40 PPT-slow and 40 STAPM. And while looking at uProf, SOC wattage never goes above 30 watts. Is this a glitch of is it just a lock on my laptop
OS: Manjaro Deepin @ kernel 4.19
Machine: Lenovo ideapad 330(15arr 2018) Ryzen 2700u

**Comment by sibradzic** [comment]
What are you using to power-stress the CPU/GPU? Many CPU stress tests can't go over ~27W... Have you tried mprime 'Small FFTs'?

**Comment by sibradzic** [comment]
interesting. what wattage is the adapter rated for?
I guess i should close this issue now...

**Comment by Kenryov** [comment]
The 45w charger that came with mine is 20V*2.25A.
Yeah... Ill play with STAPM later I'm going to try the reddit method as while this one is easier its not permanent although later ill probably make some scripts to have a regular mode and then another one for gaming
